<?php

namespace Gestion\ArticlesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    
    
    public function getLigneCmdByCmd() {
        
     return   $this->getEntityManager()
            ->createQuery(
                'SELECT lgCmd FROM GestionArticlesBundle:LignesCommande lgCmd '
            )
            ->getResult();
        
        
    }
    
    
    public function addPaiement($montant, MoyensPaiement $mp) {
        
        $paiement = new Paiements($montant, $this, $mp);
        
        
        
    }
    
    
    public function getTotalHtlignesCommandes($id){ // exemple retourne la somme ht des lgCmd 
        return   $this->getEntityManager()
            ->createQuery(
                'SELECT SUM(lgCmd.prixHt) '
                    . 'FROM GestionArticlesBundle:LignesCommande lgCmd'
                    . ' WHERE lgCmd.commande = :id '
            )->setParameter('id', $id )
            ->getResult();
        
    }
    
    
    
    
}
