<?php

namespace Gestion\ArticlesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LignesCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignesCommandeRepository extends EntityRepository
{
    
        public function getLgnCmdTechByClient($client) {

//            $req2 = 'SELECT lc.detail FROM GestionArticlesBundle:LignesCommande lc where lc.commande IN (:cmds) AND lc.technique = 1';
            
//            $listeCommande  = $this->getEntityManager()
//                        ->createQuery('SELECT c.id FROM GestionArticlesBundle:Commandes c where c.client = :id ')->setParameter('id', $client)
//                        ->getResult();
           
//            $listeLG  = $this->getEntityManager()
//                        ->createQuery($req2)->setParameter('cmds', $listeCommande)
//                        ->getResult();

    $reqJoin = 'SELECT lc.detail , c.id , c.dateCmd ' 
                .'FROM GestionArticlesBundle:LignesCommande lc '
                .'LEFT JOIN GestionArticlesBundle:Commandes c '
                . 'WITH lc.commande = c.id '
                . 'WHERE lc.detail IS NOT NULL '
                .'AND c.client = :idclient ';
            
            $listeLG  = $this->getEntityManager()
                        ->createQuery($reqJoin)
                        ->setParameter('idclient', $client)
                        ->getResult();
            
            
            
        return $listeLG;
    }

}
