security:
    encoders:
        Gestion\ClientsBundle\Entity\User : sha512
            
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SALARIE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
            
        main:
            pattern: /
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
            remember_me:
                key: "%secret%"
                lifetime: 2232000
          
                
                
        
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      #  - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/parametres/, role: ROLE_ADMIN }
        - { path: ^/gestion/, role: ROLE_ADMIN }