<?php

namespace Gestion\ClientsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RendezVousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezVousRepository extends EntityRepository
{
}
