parameters:
#    gestion_clients.example.class: Gestion\ClientsBundle\Example

services:
#    gestion_clients.example:
#        class: %gestion_clients.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
